### ISSUE TITLE
This program is blocked by group policy. For more information, contact your system administrator

### ISSUE THREAD

**Issue by brkastner** [brkastner/SDownload#76]
``` bash
at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at SDownload.Dialogs.UpdateAvailableDialog.DownloadAndInstall(Int32 size)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by brkastner** [comment]
Fixed in latest commit
